# Generated by Django 5.1.7 on 2025-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('participants', models.TextField()),
                ('fichier_retranscription', models.FileField(blank=True, null=True, upload_to='retranscriptions/')),
            ],
        ),
    ]
